# mathematical and trignometrical functions using Numpy
from numpy import *
a = array([54, 73, 2, 80, 12])
print(a)
print("sine")
print(sin(a))
print("cosine")
print(cos(a))
print("tan")
print(tan(a))
print("log")
print(log(a))
print("sqrt")
print(sqrt(a))
print("sort")
print(sort(a))
print("max")
print(max(a))
print("min")
print(min(a))
print("sum")
print(sum(a))
